<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxjzkUl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxjzkUl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxjzkUl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxjzkUl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxjzkUl\App_KernelDevDebugContainer([
    'container.build_hash' => 'PxjzkUl',
    'container.build_id' => '34ffdab9',
    'container.build_time' => 1711580296,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxjzkUl');
